# Generated by Django 3.0.8 on 2020-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qabul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_birth', models.DateTimeField()),
                ('place_birth', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('passport', models.CharField(max_length=9)),
                ('study', models.CharField(max_length=90)),
                ('year', models.DateTimeField()),
                ('diplom', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('New', 'Yangi'), ('Read', "O'qilgan"), ('Close', 'Yopilgan')], default='New', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
