# Generated by Django 3.0.8 on 2020-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabul',
            name='date_birth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
