# Generated by Django 3.0.8 on 2020-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200826_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabul',
            name='branch',
            field=models.CharField(choices=[('Magistr', 'Magistr'), ('Bakalavr', 'Bakalavr')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
