# Generated by Django 3.0.8 on 2020-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_qabul_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabul',
            name='d_photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='qabul',
            name='p_photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='qabul',
            name='photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
    ]
