# Generated by Django 3.0.8 on 2020-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200827_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabul',
            name='d_photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='p_photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='photo',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
    ]
