# Generated by Django 3.1 on 2020-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200827_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabul',
            name='photo',
            field=models.ImageField(blank=True, upload_to='file/'),
        ),
    ]
