# Generated by Django 2.1.3 on 2020-08-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200831_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qabul',
            name='branch',
        ),
        migrations.AddField(
            model_name='qabul',
            name='branchs',
            field=models.CharField(choices=[('Magistr', 'Magistr/Iqtisodiyot'), ('Bakalavr', 'Bakalavr')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qabul',
            name='d_photo',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='p_photo',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='photo',
            field=models.FileField(upload_to='file/'),
        ),
    ]
