# Generated by Django 2.1.3 on 2020-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200831_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qabul',
            old_name='d_photo',
            new_name='diplom_photo',
        ),
        migrations.RenameField(
            model_name='qabul',
            old_name='p_photo',
            new_name='passport_photo',
        ),
        migrations.RenameField(
            model_name='qabul',
            old_name='photo',
            new_name='photo3x4',
        ),
        migrations.RemoveField(
            model_name='qabul',
            name='branchs',
        ),
        migrations.AddField(
            model_name='qabul',
            name='direction_of_study',
            field=models.CharField(choices=[('5230300', 'Бакалавриат/Управление бизнесом (АПК)'), ('5230102', 'Бакалавриат/Экономика (сельское хозяйство)'), ('5410500', 'Бакалавриат/Технология хранения и переработки сельскохозяйственной продукции (по видам продукции)'), ('5411200', 'Бакалавриат/Декоративное садоводство и озеленение'), ('5411400', 'Бакалавриат/Технология переработки животной продукции'), ('5410602', 'Бакалавриат/Зооинженерия: пчеловодство'), ('5410800', 'Бакалавриат/Лесоводство'), ('5А410501', 'Магистратура/Технология хранения и переработки сельскохозяйственной продукции (по видам продукции)'), ('5А230102', 'Магистратура/Экономика (сельское хозяйство)'), ('5А233301', 'Магистратура/Агробизнес и инвестиционная деятельность')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
