# Generated by Django 2.1.3 on 2020-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200831_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
