# Generated by Django 2.1.3 on 2020-08-31 11:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200831_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone',
        ),
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
