# Generated by Django 2.1.3 on 2020-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200831_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
