# Generated by Django 2.1.3 on 2020-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200831_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='title3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='qabul',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', "Ko'rib chiqilmoqda"), ('Принято', 'Qabul qilindi')], default='На рассмотрении', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
